//
// Generated file, do not edit! Created by nedtool 5.4 from basicmsg.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __BASICMSG_M_H
#define __BASICMSG_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>basicmsg.msg:17</tt> by nedtool.
 * <pre>
 * message BasicMessage
 * {
 *     int source;
 *     int destination;
 *     int scalar_clock;
 * }
 * </pre>
 */
class BasicMessage : public ::omnetpp::cMessage
{
  protected:
    int source;
    int destination;
    int scalar_clock;

  private:
    void copy(const BasicMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BasicMessage&);

  public:
    BasicMessage(const char *name=nullptr, short kind=0);
    BasicMessage(const BasicMessage& other);
    virtual ~BasicMessage();
    BasicMessage& operator=(const BasicMessage& other);
    virtual BasicMessage *dup() const override {return new BasicMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getScalar_clock() const;
    virtual void setScalar_clock(int scalar_clock);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BasicMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BasicMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __BASICMSG_M_H

